language: python
python:
    - "3.6"      # current default Python on Travis CI

install:
  - pip install AWSIoTPythonSDK
  - pip install boto3

script:
#  - python Tests/runTests.py
  - pytest Source/test.py